name: Update Line Count Badge

on:
  push:
    branches:
      - master

jobs:
  count-lines:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Count lines of code
        run: |
          cloc --exclude-dir=node_modules .

      - name: Update badge
        run: |
            ./bin/cloc.exe --exclude-dir=node_modules .
